### ISSUE TITLE
Blocks and compatibility with WPML

### ISSUE THREAD

**Issue by vyskoczilova** [pivvenit/acf-composer-bridge#7] opened 2020-04-15 10:46 UTC
Hi,

I've built some blocks for a theme and used ACF composer integration for doing that. But I had to install a plugin version to make it work with WPML & translatable options 🙁 Could you fix that?

The "Translation preferences - What to do with the field's value when the post/page is going to be translated" radio list is not displayed.

Maybe I'm just missing something, but it doesn't work :( and your help is appreciated

My composer.json

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://pivvenit.github.io/acf-composer-bridge/composer/v3/library/"
        }
    ],
    "require": {
        "advanced-custom-fields/advanced-custom-fields-pro": "^5.8",
    }
}
```

**Comment by Qrious** [comment] 2020-04-17 09:54
From your description it seems to me that this does not seem to be an issue with our bridge, since our bridge/plugin only provides a way to install ACF via composer.

> But I had to install a plugin version to make it work with WPML & translatable options
Do you mean by this that you had to use a specific version of ACF to make it work?

I'll try to point you in the right direction if this is not a bug in our installer/bridge

**Comment by vyskoczilova** [comment] 2020-05-06 16:05
Hi @Qrious, sorry for the late reply, I've missed the notification from Github :(

I load the ACF from Composer and somehow WPML plugin is not compatible with it. But maybe this is more WPML bug than yours. I'll try to check how they check for ACF installed, maybe they are trying to find it within plugins, not by class or something...

**Comment by Qrious** [comment] 2020-05-07 06:41
> I'll try to check how they check for ACF installed, maybe they are trying to find it within plugins, not by class or something...

That seems like a very plausible explanation for the problem. I've seen these types of checks before unfortunately :(

I'm closing this issue for now, as it seems that it is not related to our installer.
However if your analysis turns out that it is related to our installer, feel free to reopen.

**Closed by Qrious** 2020-05-07 06:41 UTC
Labels: question
